export const DEFAULT_DURATION = 60;
export const DEFAULT_DURATION_MILLIS = DEFAULT_DURATION * 1000;
export const UNTITLED = "Untitled";
export const NO_PROJ_NAME = "Unnamed";
export const DEFAULT_SESSION_THRESHOLD_SECONDS = 60 * 15;
export const DEFAULT_SERVER_PING_MESSAGE_DURATION = DEFAULT_DURATION_MILLIS * 10;